'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import type { ReportCardsSuggestion } from '@/lib/school/grades-to-bulletins';
import { FileText } from 'lucide-react';

interface Props {
  suggestion?: ReportCardsSuggestion | null;
}

export function ReportCardsCta({ suggestion }: Props) {
  if (!suggestion || suggestion.enrolledCount === 0) return null;

  const qs = new URLSearchParams({
    classId: suggestion.classId,
    semester: suggestion.semester,
    year: suggestion.academicYear,
  });

  return (
    <div className="rounded-lg border border-primary/25 bg-primary/5 p-3 text-sm space-y-2">
      {suggestion.autoGenerated && suggestion.generatedCount ? (
        <p>
          <strong>{suggestion.generatedCount}</strong> bulletin(s) provisoire(s) généré(s)
          automatiquement (complétude moyenne {suggestion.coveragePct}%).
        </p>
      ) : (
        <p>
          Complétude notes : <strong>{suggestion.coveragePct}%</strong> en moyenne
          {suggestion.evaluationSlots > 0 && (
            <>
              {' '}
              ({suggestion.evaluationSlots} évaluation(s) attendue(s) ·{' '}
              {suggestion.studentsFullyComplete}/{suggestion.enrolledCount} élèves complets)
            </>
          )}
          .
          {suggestion.ready
            ? ' Vous pouvez générer les bulletins provisoires.'
            : ' Continuez la saisie pour atteindre 60% de complétude.'}
        </p>
      )}
      <Button size="sm" variant="outline" asChild>
        <Link href={`/etablissement/bulletins?${qs.toString()}`}>
          <FileText className="h-3 w-3 mr-1" />
          Voir les bulletins
        </Link>
      </Button>
    </div>
  );
}
