'use server';

import { createClient } from '@/lib/supabase/server';
import { generateReportCards } from '@/lib/actions/school';
import { evaluateClassCompleteness } from '@/lib/school/report-card-completeness';

export interface ReportCardsSuggestion {
  classId: string;
  semester: string;
  academicYear: string;
  enrolledCount: number;
  studentsWithGrades: number;
  coveragePct: number;
  evaluationSlots: number;
  studentsFullyComplete: number;
  ready: boolean;
  requiredPerSubject?: number;
  totalMissingSlots?: number;
  studentsWithGaps?: number;
  hasGaps?: boolean;
  gapSummary?: string;
  includedExamTypes?: string[] | null;
  includedExamTypesLabel?: string | null;
  levelBandLabel?: string | null;
  periodLabel?: string | null;
  autoGenerated?: boolean;
  generatedCount?: number;
  error?: string;
}

const DEFAULT_MIN_COVERAGE = 60;

export async function evaluateReportCardReadiness(
  orgId: string,
  classId: string,
  semester: string,
  academicYear: string,
  includedExamTypes?: string[] | null
): Promise<Omit<ReportCardsSuggestion, 'autoGenerated' | 'generatedCount' | 'error'>> {
  const supabase = await createClient();

  const [{ data: students }, { data: grades }, { data: evaluations }] = await Promise.all([
    supabase
      .from('school_students')
      .select('id')
      .eq('organization_id', orgId)
      .eq('class_id', classId)
      .eq('enrollment_status', 'enrolled'),
    supabase
      .from('school_grades')
      .select('student_id, subject_id, exam_type, score, max_score, school_subjects(coefficient)')
      .eq('organization_id', orgId)
      .eq('class_id', classId)
      .eq('semester', semester)
      .eq('academic_year', academicYear),
    supabase
      .from('school_grade_evaluations')
      .select('subject_id, exam_type, max_score, coefficient')
      .eq('organization_id', orgId)
      .eq('class_id', classId)
      .eq('semester', semester)
      .eq('academic_year', academicYear),
  ]);

  const { filterByIncludedExamTypes } = await import('@/lib/school/bulletin-exam-types');
  const { mapGradesWithEvaluationMeta } = await import('@/lib/school/grade-evaluation-meta');

  const enrolledIds = (students ?? []).map((s) => s.id as string);
  const gradeRows = mapGradesWithEvaluationMeta(
    filterByIncludedExamTypes(
      (grades ?? []).map((g) => ({
        studentId: g.student_id as string,
        subjectId: g.subject_id as string,
        examType: (g.exam_type as string) ?? 'default',
        score: Number(g.score),
        maxScore: Number(g.max_score) || 20,
        coefficient: Number((g.school_subjects as { coefficient?: number })?.coefficient ?? 1),
      })),
      includedExamTypes
    ),
    (evaluations ?? []).map((e) => ({
      subject_id: e.subject_id as string,
      exam_type: e.exam_type as string,
      max_score: e.max_score,
      coefficient: e.coefficient,
    }))
  );

  const completeness = evaluateClassCompleteness({
    classId,
    semester,
    academicYear,
    enrolledStudentIds: enrolledIds,
    evaluationSlots: filterByIncludedExamTypes(
      (evaluations ?? []).map((e) => ({
        subjectId: e.subject_id as string,
        examType: e.exam_type as string,
      })),
      includedExamTypes
    ),
    grades: gradeRows,
    minPct: DEFAULT_MIN_COVERAGE,
  });

  return {
    classId,
    semester,
    academicYear,
    enrolledCount: completeness.enrolledCount,
    studentsWithGrades: completeness.studentsWithAnyGrade,
    coveragePct: completeness.averageCompletenessPct,
    evaluationSlots: completeness.evaluationSlots,
    studentsFullyComplete: completeness.studentsFullyComplete,
    ready: completeness.ready,
  };
}

/** Évalue la couverture notes et génère les bulletins provisoires si le seuil est atteint. */
export async function autoGenerateReportCardsAfterGrades(
  orgId: string,
  classId: string,
  semester: string,
  academicYear: string,
  options?: { auto?: boolean; minCoveragePct?: number }
): Promise<ReportCardsSuggestion> {
  const evaluation = await evaluateReportCardReadiness(
    orgId,
    classId,
    semester,
    academicYear
  );

  const minPct = options?.minCoveragePct ?? DEFAULT_MIN_COVERAGE;
  const ready = evaluation.coveragePct >= minPct && evaluation.enrolledCount > 0;

  const result: ReportCardsSuggestion = {
    ...evaluation,
    ready,
  };

  if (!options?.auto || !ready) return result;

  const supabase = await createClient();
  const { data: org } = await supabase
    .from('organizations')
    .select('settings')
    .eq('id', orgId)
    .maybeSingle();
  const { parseSchoolOrgSettings } = await import('@/lib/school/school-org-settings');
  const schoolSettings = parseSchoolOrgSettings(
    (org?.settings as Record<string, unknown>) ?? null
  );
  const defaultTypes =
    schoolSettings.bulletin_default_exam_types.length > 0
      ? schoolSettings.bulletin_default_exam_types
      : null;

  const gen = await generateReportCards(classId, semester, academicYear, {
    includedExamTypes: defaultTypes,
  });
  if ('error' in gen && gen.error) {
    return { ...result, error: gen.error, autoGenerated: false };
  }

  return {
    ...result,
    autoGenerated: true,
    generatedCount: gen.count ?? 0,
  };
}
